/**
 * Regenerates spec/conformance/bucketing.json from the reference implementation.
 *
 * Deterministic: the same source produces a byte-identical fixture, so a diff
 * here always means the hash changed, never that the generator wandered.
 *
 * Regenerating is a deliberate, reviewed act. It is NEVER the way to make a
 * failing SDK pass — see spec/BUCKETING.md.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bucketFor, bucketingInput } from '../src/bucketing.ts';
import { murmurHash3x86_32String } from '../src/murmur.ts';

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = join(here, '..', '..', '..', 'spec', 'conformance', 'bucketing.json');

/** Seeded LCG (Numerical Recipes constants) so generation never depends on Math.random. */
function makeRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

const random = makeRandom(0x5eed);

function pick<T>(items: readonly T[]): T {
  return items[Math.floor(random() * items.length)]!;
}

const FLAG_KEYS = [
  'checkout-redesign',
  'new-search',
  'a',
  'flag.with.dots',
  'flag_with_underscores',
  'flag-with-a-very-long-key-name-that-exceeds-a-single-hash-block',
];

const SALTS = ['salt-a', 'salt-b', '0', 'f47ac10b-58cc-4372-a567-0e02b2c3d479'];

/**
 * Deliberately includes the cases that break naive ports: every tail length
 * (len % 4), multi-byte UTF-8, astral-plane characters, and the empty string.
 */
const EDGE_KEYS = [
  '',
  'a',
  'ab',
  'abc',
  'abcd',
  'abcde',
  'é',
  'ünïcödé-user',
  'ユーザー',
  '用户-42',
  'user-🎉',
  '🎉🎉🎉',
  'Ω'.repeat(64),
  'x'.repeat(255),
  '0',
  '00000000-0000-0000-0000-000000000000',
];

interface Case {
  flagKey: string;
  salt: string;
  bucketKey: string;
  input: string;
  hash: number;
  expectedBucket: number;
}

const cases: Case[] = [];
const seen = new Set<string>();

function addCase(flagKey: string, salt: string, bucketKey: string): void {
  const input = bucketingInput(flagKey, salt, bucketKey);
  if (seen.has(input)) return;
  seen.add(input);
  cases.push({
    flagKey,
    salt,
    bucketKey,
    input,
    hash: murmurHash3x86_32String(input, 0),
    expectedBucket: bucketFor(flagKey, salt, bucketKey),
  });
}

// Edge cases first, across every flag/salt combination.
for (const flagKey of FLAG_KEYS) {
  for (const salt of SALTS) {
    for (const bucketKey of EDGE_KEYS) {
      addCase(flagKey, salt, bucketKey);
    }
  }
}

// Then fill out to a broad sample of ordinary keys.
const TARGET = 500;
let n = 0;
while (cases.length < TARGET) {
  addCase(pick(FLAG_KEYS), pick(SALTS), `user-${n}`);
  n += 1;
}

const fixture = {
  version: 1,
  note: 'Generated by packages/core/scripts/generate-fixture.ts. See spec/BUCKETING.md. Do not hand-edit.',
  algorithm: 'MurmurHash3_x86_32(flagKey + ":" + salt + ":" + bucketKey, seed=0) % 100000',
  bucketSpace: 100_000,
  cases,
};

writeFileSync(fixturePath, JSON.stringify(fixture, null, 2) + '\n', 'utf8');
console.log(`wrote ${cases.length} cases to ${fixturePath}`);
